[project]
name = "pyvec-docs"
version = "0"
requires-python = "==3.12.*"
dependencies = [
    "jinja2==3.1.6",
    "myst-parser==4.0.1",
    "pydantic==2.11.4",
    "requests==2.32.3",
    "sphinx-rtd-theme==3.0.2",
    "sphinx==8.2.3",
    "sphinxemoji==0.3.1",
]

[dependency-groups]
dev = [
    "pytest-ruff==0.4.1",
    "pytest==8.3.4",
    "sphinx-autobuild==2024.10.3",
]

[build-system]
requires = ["uv_build>=0.7.3,<0.8.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = "tests"
addopts = "--ff --ruff --ruff-format"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2
