name: Generate Grants
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Generate the list of grants
      run: uv run python _scripts/generate_grants.py > ./operations/grants.rst
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "update the list of grants (generated)"
        branch: automation/grants
        title: "Automated update of the list of grants"
        body: >
          Automated update of the list of grants :robot:
          For details, see [the docs](https://docs.pyvec.org/CONTRIBUTING.html#skript-na-generovani-zapisu-hlasovani-o-grantech) :book:
