name: Update Pages
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Generate the list of grants
      run: uv run python scripts/generate_grants.py > ./docs/operations/grants.rst
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate the list of boards
      run: uv run python scripts/generate_boards.py > ./docs/operations/boards.rst
    - name: Create PR
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        add-paths: |
          ./docs/operations/grants.rst
          ./docs/operations/boards.rst
        commit-message: "update pages (generated)"
        branch: automation/pages
        title: "Automated update of pages (grants, boards)"
        body: >
          Automated update of some pages, namely the lists of grants and boards :robot:
          For details, see [the docs](https://docs.pyvec.org/contributing.html) :book:
